### ISSUE TITLE
Add team photo to GitHub repo README and/or docs folder

### ISSUE THREAD

**Issue by A-PS1999** [UoB-COMSM0110/2024-group-1#1]

**Comment by RicardoMiles** [comment]
I have uploaded the team photo and a demo animation video of the Paperprototype. Additionally, I have updated the first part of the README.md for everyone to fill in.

All visual media materials have been embedded using Markdown syntax within the README.md file.

The animation demo of the Paper prototype has been appropriately edited, providing a linked version, a repository source file version, and a GIF thumbnail version.

Images such as the source files for the team photo have been categorized into the new "image" folder I created.


Please, whenever it's convenient for you, could you also provide the paper prototype demonstration for idea 2 and include it in the README.md for an update? Thank you!
