### ISSUE TITLE
Fix the multiple enemies display bug

### ISSUE THREAD

**Issue by RicardoMiles** [UoB-COMSM0110/2024-group-1#104]
Hey @A-PS1999  Sam！
I've changed the enemies that will be encountered in hardmode and easymode, the display of the ENEMIES  (≥2 enemies) will overlap when doubling enemies.
Would you mind improving that on ```random-combat=improvement```
![屏幕截图 2024-04-27 184314](https://github.com/UoB-COMSM0110/2024-group-1/assets/150692986/b1094b18-2b7c-4881-bcea-9550ac3a3077)

**Comment by A-PS1999** [comment]
Hey Ricardo, I think I have fixed this bug in my latest push to `random-combat-improvement`. Of course, please check and let me know if it all looks OK to you. If so, please close this issue.

**Comment by RicardoMiles** [comment]
Thanks Sam, 
It looks better right now. I'll close it.
