### ISSUE TITLE
Create the Use-Case Specification.md

### ISSUE THREAD

**Issue by erer1022** [UoB-COMSM0110/2024-group-1#13]
Dear Team,

I've completed the use-case specification in my own branch 'https://github.com/UoB-COMSM0110/2024-group-1/blob/LanaiTest/docs/Use_Case_Specification.md'. Welcome to any suggestions and modifications or any detailed information you'd like to add into it.
@RicardoMiles @erer1022 @A-PS1999 @Doctor-TOTORO @JThakral20
Thank you all!!

**Comment by A-PS1999** [comment]
Hi @erer1022, thanks for starting on this. I've already done one update on this which I have pushed to the branch, but I think the alternative flow needs to be improved as it doesn't appear to match with alternative flow section's intended use.

Here's an article which goes over use case specification documents:
https://www.visual-paradigm.com/guide/use-case/what-is-use-case-specification/

The key thing in this article about how the alternative flow works is that it represents a path which doesn't lead to the intended goal (in our case, beating the game). You could also refer to the 2023 example to see what the alternative flow should look more like.

**Comment by erer1022** [comment]
Hi @A-PS1999 
Thank you for the suggestion and for updating the documentation :D

I want to extend an apology in advance for any confusion: the initial document was edited by @Doctor-TOTORO. Due to an accidental click on "convert to issue," it now appears under my work, but it truly belongs to Lanai's branch. 
The article reference you shared is greatly appreciated. We will review it and refine our documents accordingly.

**Comment by Doctor-TOTORO** [comment]
Hi @A-PS1999 
Thanks for the modification, I have also modified the alternative flow with explanation of ending game innormaly. But I'm afraid maybe it's not quite a complete alternative flow with all the innormal circumstances, if possible please tell me which can be added in or you can just modify it directly.
Thanks a a lot.

**Comment by RicardoMiles** [comment]
Hi @Doctor-TOTORO @A-PS1999
 I corrected some typos in the alternative process and added a core rule to the gameflow. If you could check for any logical conflicts, that would be great. Thank you very much.

**Comment by A-PS1999** [comment]
Hey @RicardoMiles, I have updated the use case specification further to your previous update. Please refer to #14 which will show the commit history for that pull request.

I removed the extension point section from the end, as I'd argue it's inappropriate for that section to be in the use case specification. In addition, I removed the step in the basic flow of fully healing after each battle, given our discussion in the last workshop that it would be more interesting for the game to offer a tradeoff between health and movement/action points.

If you think that #14 looks good, please go ahead with a merge of that pull request into `main`.

**Comment by RicardoMiles** [comment]
Hey @A-PS1999 Thanks for your recent updates to the use case specification. I have reviewed the modifications, particularly those detailed in #14, and I find them to be both thoughtful and well-reasoned. 


The changes contribute to the project's overall development resonably. Accordingly, I will proceed with merging the pull request into the main branch.

**Comment by A-PS1999** [comment]
Closing this issue now, as it has been merged.
