### ISSUE TITLE
Add initial class diagram

### ISSUE THREAD

**Issue by A-PS1999** [UoB-COMSM0110/2024-group-1#15]
Based on the outline we created in the workshop today (19/02/2024), a class diagram of our game needs to be made. This might be updated in the future but it'd be good to have one sorted this week.

**Comment by RicardoMiles** [comment]
Hi @A-PS1999 I have uploaded a draft class diagram to class diagram branch #which is updated with the latest classes's attributes and method of your branches, but not entirely covers all of class. If you notice any typos or inaccuracies, please let me know. Thank you!

**Comment by A-PS1999** [comment]
> Hi @A-PS1999 I have uploaded a draft class diagram to class diagram branch #which is updated with the latest classes's attributes and method of your branches, but not entirely covers all of class. If you notice any typos or inaccuracies, please let me know. Thank you!

Hey @RicardoMiles , if you think this is ready to merge into `main` or for someone to look at, please submit a pull request for this.

**Comment by RicardoMiles** [comment]
Hi @erer1022 
Please update class diagram to latest codes version on 'add-class-diagram' branch later! 
Thank you!

**Comment by A-PS1999** [comment]
Hey @erer1022, @RicardoMiles and @Doctor-TOTORO, this message is just a reminder to work on this at some point. At this point the structure of the program and the classes in use are more concrete, so I think it's good that we start moving towards having a class diagram we can add to the repo.

**Comment by erer1022** [comment]
Thank you for your reminder, Sam. Can we modify the class diagram during the Spring vacation?

**Comment by A-PS1999** [comment]
> Thank you for your reminder, Sam. Can we modify the class diagram during the Spring vacation?

If it's not going to be done before then, it definitely needs to be done over the spring break, yes.

**Comment by A-PS1999** [comment]
@erer1022 @RicardoMiles @Doctor-TOTORO Hey, what's the situation with this?
