### ISSUE TITLE
Add images, video and discussion of paper prototyping to GitHub repo

### ISSUE THREAD

**Issue by A-PS1999** [UoB-COMSM0110/2024-group-1#2]

**Comment by A-PS1999** [comment]
Hey @RicardoMiles, I don't mean to push too hard on this but since you have some of the photos and videos which were taken at the last session it'd be great if you could upload them and update the docs.

@JThakral20, just to check, did you take any photos or video during the last workshop session? If you did it'd be great if you could upload those.

**Comment by RicardoMiles** [comment]
Please, whenever it's convenient for you, could you also provide the paper prototype demonstration for idea 2 and include it in the README.md for an update? Thank you!

**Comment by A-PS1999** [comment]
Done.
