### ISSUE TITLE
Create main menu state

### ISSUE THREAD

**Issue by A-PS1999** [UoB-COMSM0110/2024-group-1#23]
The main menu screen state of the game needs to be created (visual elements, keyboard and/or mouse interaction), with the ultimate goal of setting up the game and transitioning to the map state. An options menu or help screen might be useful here too (though that maybe should be its own state).

Assigning @erer1022 as she expressed interest in working on this state.

**Comment by erer1022** [comment]
Thank you Sam for clarifying the elements of the menu screen state. I'll try to build up a frame work for the interface in the following week.
