### ISSUE TITLE
Create map state

### ISSUE THREAD

**Issue by A-PS1999** [UoB-COMSM0110/2024-group-1#24]
The map state of the game needs to be created, with its various visual elements and controls (keyboard and/or mouse). Some coordination might be required for the transition from main menu to map, or from map to other states like combat or (if implemented) a shop.

Assigning @RicardoMiles, who expressed the desire to work on this state.

**Comment by RicardoMiles** [comment]
Hi @A-PS1999 
I have created a map state interface along with some interactive logic for keyboard and mouse input. However, there appears to be a significant gap between the OO paradigm and the main class. Therefore, I've just posted it as a UI interface and functional update. We can discuss for further improvements.

**Comment by A-PS1999** [comment]
I'm going to close this as, though the map state is in need of improvement, it has kind of been created. If you start working on improvements to it or a new version of it, feel free to make a new issue/entry on the kanban board.
