### ISSUE TITLE
Add prototype draft to Github repo

### ISSUE THREAD

**Issue by RicardoMiles** [UoB-COMSM0110/2024-group-1#3]
Hey @A-PS1999 , I don't mean to push.Please don't feel rushed at all; I'm just reminding. Since our team has two ideas, please also upload a simple storyboard animation demo for the other one to the repository whenever you find it convenient, so we can have it as source material for our discussion on Thursday.

**Comment by A-PS1999** [comment]
Closing this now as a prototype image of the second idea has been uploaded.
