### ISSUE TITLE
Rework the map screen

### ISSUE THREAD

**Issue by A-PS1999** [UoB-COMSM0110/2024-group-1#45]
Hey @RicardoMiles, I'm assigning you to this issue as the map state needs to be improved and there aren't any currently active issues/kanban items about it.

In this recent pull request of mine (#44) I edited out the line in your map state which was clipping the screen, as it was causing a lot of problems with rendering generally. The map screen in general needs to be reworked as it currently isn't that responsive and the nodes are very widely scattered. I would suggest simplifying it if necessary.

**Comment by RicardoMiles** [comment]
Got it.I will simplify at least one map before Friday and update the list of maps we will finally use.

**Comment by A-PS1999** [comment]
Thanks. Now that #44 has been merged with `main` you can work on this a little more easily. I'd try find a way to create the map screen without having to use the `clip` function. If you find that you absolutely must use it, please find a way of having it not interfere with the rendering of other game states.

**Comment by RicardoMiles** [comment]
Major breakthrough, refactor map interface UI, refactor map data structure, and state interaction logic.
Stored map data by writing a design ```.JSON``` file.
Achieved normal rendering and interaction logic of the map during rendering by reading the JSON file and refactoring the node class. @A-PS1999 

Implemented the operation to return to the menu state.
Shop icons have been created, and relevant logic has been drafted with comments, awaiting further refinement after completion of the shop state. @JThakral20 No worries! Enjoy your holiday, and feel free to reach out to me anytime if there's any progress on the shop state.

The code have been updated in both the ```build``` and ```src``` folders. I assure that all the code on the branch is executable and does not affect other teammates' code.

**Comment by A-PS1999** [comment]
Thanks @RicardoMiles, I'll close this issue and move it to 'Done' in the kanban board now, as this looks much better and more successful for the map screen. Any further refinements you do to the map screen can be done under a separate issue/ticket on the kanban board if you'd like to do that.
