### ISSUE TITLE
Bugfix required on EndState

### ISSUE THREAD

**Issue by A-PS1999** [UoB-COMSM0110/2024-group-1#46]
Hey @Doctor-TOTORO, I can see at least one bug that needs fixing in `EndState`.

I get an error which is caused by the background image you're trying to load being bigger than the window size. I think this would be a pretty easy thing to fix, but I am making this issue to bring it to your attention so that you can fix it.

Important note: Please wait until this pull request has been merged (#44) before you work on this, so as to avoid merge conflicts and accidentally uploading out-of-date code.

**Comment by Doctor-TOTORO** [comment]
Ok I will fix it later😀

**Comment by A-PS1999** [comment]
OK, I've merged #44 so you can work on this now. Of course, make sure your branch is up to date with `main` when you do so.

**Comment by Doctor-TOTORO** [comment]
I have changed the size of button and image in endstate branch, it should be work now.

**Comment by A-PS1999** [comment]
Cool. If you think it's ready to be merged, please submit a pull request and one of us can take a look.

**Comment by A-PS1999** [comment]
Closing this now as @Doctor-TOTORO resolved it with the pull request #47.
