### ISSUE TITLE
EndState needs to be able to return to updated map

### ISSUE THREAD

**Issue by A-PS1999** [UoB-COMSM0110/2024-group-1#51]
Hey @RicardoMiles and @Doctor-TOTORO, I'm pointing this issue out to both of you as it's something which I think both of you need to be aware of. It's also possibly something which I think you might want to coordinate on when it comes to implementing this.

Currently it's possible to get all the way from the menu to the map, into combat and then to the end screen, but not any further than that. What needs to happen is that when the player presses the 'Continue' button on the end screen, they're taken back to the map. The map should be updated so that the player cannot go backwards, but instead is able to select nodes from the level above the one they just went through.

It'd be great if this could be worked on as it's a key missing part of the gameplay loop which we need for being able to call the game 'beatable'.

**Comment by RicardoMiles** [comment]
It is exactly the game flow works that "When the player presses the 'Continue' button on the end screen, they're taken back to the map. ". 
I have thought how to use the stack to store data when changing to other screen. Permanently storing map data until the player lose the whole game should be fundamental for my method design for @Doctor-TOTORO  to use.
Would you mind simply explaining the stack design pattern and the way to use our own stack. It would be great for me you know it further. Thanks a lot @A-PS1999 !

**Comment by A-PS1999** [comment]
Hey Ricardo, I was expecting that you'd already have some idea of how you'd get the map state to persist and update.
Off the top of my head I imagine that the easiest approach for updating the map would be to have a map state-related class initialized and stored in the game engine, so that it can be accessed and updated throughout.

Hopefully that helps you get an idea of how you can implement this important feature. Otherwise, perhaps we could call at some point to discuss this. It'd be easier to discuss that way than on here.

**Comment by A-PS1999** [comment]
@RicardoMiles @Doctor-TOTORO 
How's this going?

**Comment by RicardoMiles** [comment]
Hey @A-PS1999 We are almost there, I just got back from my grandfather's funeral in CN. I had talked to Totoro before my flight. We are trying to make the flow work and almost there. I think we could make it work before this Friday!
