### ISSUE TITLE
writing process section of report

### ISSUE THREAD

**Issue by JThakral20** [UoB-COMSM0110/2024-group-1#54]

**Comment by A-PS1999** [comment]
Do you have a separate branch for working on this?

FYI I've created a branch where I've added an intro section to the readme and am currently working on improving and adding to the requirements section. I intend to work on the implementation section as well, after I've finished with this one.

**Comment by JThakral20** [comment]
Hey yes I will have a separate branch for the process section. I'm thinking I can probably do the conclusion as they lead into each other? 
And great thank you that sounds good.

**Comment by A-PS1999** [comment]
Closing this as it's been done.
