### ISSUE TITLE
Writing Design section of report

### ISSUE THREAD

**Issue by RicardoMiles** [UoB-COMSM0110/2024-group-1#66]
@erer1022 @Doctor-TOTORO We could work on that together.

**Comment by RicardoMiles** [comment]
@Doctor-TOTORO @erer1022 I've already written a draft text report for this section.Please let me know if there is any inappropriate word, please insert the image in the responsive position, the final version of the class diagram will only show the most basic classes mentioned, the amount of the process can be put up, the class diagram sketches can also be uploaded during the whiteboard discussion!

**Comment by RicardoMiles** [comment]
Hi team! @A-PS1999 @JThakral20 If possible, I'd love your comments on the parts I've written in ```README.md``` !

**Comment by A-PS1999** [comment]
Hey @RicardoMiles, I've taken a look and overall I think it's good. Later on, maybe after it's merged in but possibly before, I might go through and amend a few bits as I see there are a few little mistakes. I like the table providing an outline of the different classes.

**Comment by JThakral20** [comment]
Hey @RicardoMiles yeah agreed I think it looks good, just a few typos here and there which will be easy to fix

**Comment by RicardoMiles** [comment]
Thanks@A-PS1999 Sam @JThakral20 Jasmine. Feel free to amend! I will appreciate.

I just listed part of our class that I thought is most important, I can write more in same format, would you mind suggesting other classes that should be involved,@A-PS1999 Sam?

**Comment by A-PS1999** [comment]
> Thanks@A-PS1999 Sam @JThakral20 Jasmine. Feel free to amend! I will appreciate.
> 
> I just listed part of our class that I thought is most important, I can write more in same format, would you mind suggesting other classes that should be involved,@A-PS1999 Sam?

Hey @RicardoMiles, I think that class section is already good enough as an overview. How many words do you have left in the design section? Remember that our rough word count for the section is about 750 words.

If you still have space to add to that section, I think you could discuss a bit more in-depth about the JSON map saving/loading if you like, as it's something I only touch lightly upon in the implementation section later.

**Comment by A-PS1999** [comment]
Note: I pushed some amendments to the design section just now.

**Comment by RicardoMiles** [comment]
Hey Sam@A-PS1999 
I thought json design part was necessary to add, and I have. However, the word count seems to exceed 200 words, If the table doesn't count as a word count we haven't exceeded the word limit. so I'm asking for your help in streamlining it, feel free to amend.

**Comment by A-PS1999** [comment]
Hey @RicardoMiles, I have shortened the design section a little bit, but not by much. I checked one of the 2023 project repos and their design section actually had over 1100 words, so I imagine our section is probably fine for word count (though I wouldn't add any more to it).

**Comment by A-PS1999** [comment]
@RicardoMiles Is there a communication diagram for the design section? I ask because there is a heading which says `behavioural diagram` even though there's no picture there.

**Comment by RicardoMiles** [comment]
Hi  @A-PS1999 Sam
@Doctor-TOTORO Lanai would upload it soon. She had done some amendment to it yesterday.

**Comment by A-PS1999** [comment]
OK, cool, thanks. Once that has been added in I think the design section can be merged into `main`.

**Comment by Doctor-TOTORO** [comment]
Hi @RicardoMiles @A-PS1999, I have added the behavioural diagram in docs and readme, please check if there is something wrong in the diagram and I can fix it as soon as possible.
