### ISSUE TITLE
Cleanup/improvements required for class diagram

### ISSUE THREAD

**Issue by A-PS1999** [UoB-COMSM0110/2024-group-1#77]
I hadn't had a chance to look at the class diagram before @RicardoMiles merged it, but having looked in the docs file there are a few things which I think need amending.

1. Most importantly, and I know it's tough given how large it is, but the class diagram (the document `Draft Class Diagram.pdf`) is completely illegible because the image and text is too small. We really need the text to be legible.
2. There's another document in the `docs` folder called `Class Diagram Draft.pdf` which looks like a version of the very first class diagram we did in the workshop. The problem is, these two names (`Draft Class Diagram` and `Class Diagram Draft`) are too similar which makes it confusing which is the final, proper one. Please either remove `Class Diagram Draft.pdf` if we're not actually going to end up using it or at least rename it to something like `Initial_Class_Diagram.pdf` to make things a little clearer.

**Comment by erer1022** [comment]
Hi Sam, Thank you for your suggestions. I've created a new branch to rename the initial class diagram as you recommended. Regarding the text size in the diagram, I've attempted to enlarge it previously, but it's challenging due to the high number of classes. However, increasing the zoom with 'Ctrl +' does make the file more legible. Let's discuss further if there are any specific adjustments you think could help improve clarity.

**Comment by erer1022** [comment]
Hi Sam, 
Ricardo and Lanai give me some suggestions on this issue.
I've made some adjustments to the class diagram and would appreciate your feedback. To improve visibility, I've simplified the main diagram in the "readme.md" file to only show the major classes, ensuring that the text remains readable. For a comprehensive view, I've included a link in the document that directs you to the full diagram.

Additionally, I've created another diagram that outlines the relationships between "player-deck-card" and "entity-enemy-player". 
We may add more illustration to demonstrate the relationships.
You can find this in the "design-draft-section". Please review these changes and let me know if you have any suggestions.

**Comment by A-PS1999** [comment]
Hey @erer1022, I presume one of the images you're talking about is `Class-diagram-major`? It looks mostly OK for a more condensed version of the class diagram, though I think the arrow is going the wrong direction on the relationship between the `Node` and `CombatNode`.

When you think it's ready to merge in and add to the README again, please do submit a pull request so I can review your final work.

**Comment by erer1022** [comment]
Thank you for finding that fault! I have already corrected it.
