### ISSUE TITLE
Add relevant photos to process section

### ISSUE THREAD

**Issue by JThakral20** [UoB-COMSM0110/2024-group-1#86]

**Comment by RicardoMiles** [comment]
Hey Jasmine, @JThakral20 
There is some pics we could add in this part, just in case we need them.
![WhatsApp 图像2024-04-27于18 48 47_2842832e](https://github.com/UoB-COMSM0110/2024-group-1/assets/150692986/0a56f5d0-45da-4656-858b-f72543cf34af)
![WhatsApp 图像2024-04-27于18 48 47_6d1a1180](https://github.com/UoB-COMSM0110/2024-group-1/assets/150692986/1de1c438-e960-4e46-8115-dc2c38a0882b)
![WhatsApp 图像2024-04-27于19 13 26_4c4a9be6](https://github.com/UoB-COMSM0110/2024-group-1/assets/150692986/3ad21d4e-9bbc-4b89-8c03-92f3a1949266)

**Comment by JThakral20** [comment]
Thanks Ricardo! Yeah those would definitely be good!

**Comment by A-PS1999** [comment]
Closing this as these images, as well as the Process section, have been added to `main`.
