### ISSUE TITLE
Tidy up EndState

### ISSUE THREAD

**Issue by A-PS1999** [UoB-COMSM0110/2024-group-1#89]
@Doctor-TOTORO, in keeping with the group call we had recently, please work on this issue:

- Remove all buttons except 'Continue' from `EndState`.
- Add some clear text to indicate that the player won, if they did. Do the same for if they lost, if that doesn't already exist.

**Comment by Doctor-TOTORO** [comment]
OK I'm mdoifying it, the new one would be uploaded later.

**Comment by RicardoMiles** [comment]
Hey @Doctor-TOTORO
 Is it possible to create a new branch so that the endstate fonts display properly, there will be a display overlapping problem, we .have the same problem on the lab machine and my personal 1080p resolution laptop.

**Comment by Doctor-TOTORO** [comment]
@RicardoMiles I have made some changes of the display, you could check it in the branch endstate_display now. Thank you!
