### ISSUE TITLE
Exchange the icon of HP and AP

### ISSUE THREAD

**Issue by Doctor-TOTORO** [UoB-COMSM0110/2024-group-1#92]
@RicardoMiles It looks like the icons for HP and AP are switched. Could you please fix it?

![微信图片_20240424120913](https://github.com/UoB-COMSM0110/2024-group-1/assets/101552212/99641765-86f5-448a-8815-a61de7066383)

**Comment by RicardoMiles** [comment]
Got it. I'll fix it soon!

**Comment by RicardoMiles** [comment]
It is fixed @Doctor-TOTORO Could you please have a look
