### ISSUE TITLE
Improve Game Balance on AP value system

### ISSUE THREAD

**Issue by RicardoMiles** [UoB-COMSM0110/2024-group-1#94]
Hi team! @JThakral20 @A-PS1999 @erer1022 @Doctor-TOTORO Here's a well weighed numerical balancing scheme for the game

* Player initially own 2 APs. Hi Sam, could you help me with that on ```game-blance``` branch. @A-PS1999 
* Lose a combat gain no AP, lose no AP either. Changes should be done in ```EndState.pde```.
* Win a combat gain 2 APs. Changes should be done in ```EndState.pde```.
* Skip or move step by step using mapped value between level gap and AP.  Changes should be done in ```MapState.pde```

If there are any suggestions please discuss them with me and if everyone agrees then I'll make adjustments

**Comment by A-PS1999** [comment]
Hey @RicardoMiles, I'm happy to help out but I don't see a `game-balance` branch. Do you need me to make one, or can I just contribute to the branch you're working on for this?

**Comment by RicardoMiles** [comment]
Hey Sam @A-PS1999 !
I'm sorry. It seems that I have just made a local ```game-balance``` and now we have this one on Github remote shared repo. You're welcome to contribute to it. I'll take care of changing the last three tasks（changes in ```EndState``` and ```MapState```） I just mentioned, and I'd appreciate it if you could help me with double check as well as testing when all changes have been done!

**Comment by A-PS1999** [comment]
On `game-balance` I amended the player's starting AP amount to 2.

**Comment by RicardoMiles** [comment]
After much personal trial and debugging, I've made a few tweaks to the mechanics
* In view of the increased difficulty, the player is particularly easy to die in easymode, so the initial AP adjustment to 5, AP sacrificed supplementary HP adjustment to 40
* In order to make the AP system more meaningful, I allow players to sacrifice AP to challenge bosses repeatedly in boss levels if they have extra AP.
* When repeatedly adjusting the boss, the HP of the boss will be inherited from the remaining HP of the boss when the player fails.
The following programmatic adjustments have been made to address bugs already encountered prior to the mechanic change
* Adjusted the final win display logic in EndState to prevent the final victory screen from being displayed when the player is DEFINITELY dead.
* Adjusted the music pause code to ensure seamless integration without music overlap.

Also I would like to discuss and tweak the following with @A-PS1999 Sam 

* We can lower the blood level of Worm, Golem, and Spider, you can combine them and have more than two enemies at a time in the goToCombat case, this will make the AOE（Area of effect）cards in the store more meaningful!
* I'm afraid to touch the specific monster design because it's a little complicated
* From my personal experience with card game and playing our game from a user's point of view, it's definitely more challenging and fun now that it's not just perplexingly hard or cruised to win easily!
